[colors]
black = "#101116"
white = "#f1f5f9"
orange = "#fb9b64"
orange-dark = "#bb774f"
gray = "#44475a"
cyan = "#27a1b9"
cyan-dark = "#1e5060"

[base.focused]
foreground = "white"

[base.unfocused]
foreground = "gray"

[highlight.focused]
foreground = "orange"

[highlight.unfocused]
foreground = "orange-dark"

[title.focused]
foreground = "cyan"

[title.unfocused]
foreground = "cyan-dark"

[border.focused]
foreground = "white"

[border.unfocused]
foreground = "gray"

[editor]
line_numbers = "relative"
